baseURL = "http://example.org/"
languageCode = "en-us"
title = "Open Web"

[params]
    author = "Open Web BU"
    description = "Open Web BU is BU's best club for passionate coders."
    
    stylesheet = "styles.css"
    script = "app.js"

    appsOpen = "false"
    appURL = "https://docs.google.com/forms/d/e/1FAIpQLSefRharNR_Wpm_T5_8RaCA-UJODeKvDWPU_9kV5-rkX_Lf2Rw/viewform?usp=sf_link"